services:
  - type: web
    name: klandodash
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn dash_apps.app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: PROJECT_DIR
        value: .
      - key: RESOURCE_DIR
        value: ./resources
      - key: APP_PASSWORD
        sync: false
      - key: AUTHORIZED_EMAILS
        sync: false
      - key: MAPLIBRE_API_KEY
        sync: false
      - key: MAPLIBRE_STYLE_URL
        sync: false
      - key: USE_EMBED_MODE
        value: false
