-- ==============================================================================
-- Migration: Create AI Recommendations Table
-- Description: Stores actionable insights generated by the global AI scan.
-- ==============================================================================

CREATE TYPE recommendation_type AS ENUM ('TRACTION', 'STRATEGIC', 'ENGAGEMENT', 'QUALITY');
CREATE TYPE recommendation_status AS ENUM ('PENDING', 'APPLIED', 'DISMISSED');

CREATE TABLE IF NOT EXISTS public.dash_ai_recommendations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    type recommendation_type NOT NULL,
    priority integer DEFAULT 1, -- 1: Normal, 2: High, 3: Critical
    title text NOT NULL,
    content jsonb NOT NULL, -- Stores dynamic data (message, distance, user_info, etc.)
    target_id text, -- ID of the related trip, user or request
    status recommendation_status DEFAULT 'PENDING',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Index pour la lecture rapide
CREATE INDEX idx_ai_rec_status ON public.dash_ai_recommendations(status);
CREATE INDEX idx_ai_rec_type ON public.dash_ai_recommendations(type);

-- RLS (Admin only)
ALTER TABLE public.dash_ai_recommendations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Admins can do everything on ai recommendations" 
ON public.dash_ai_recommendations FOR ALL TO authenticated USING (true);
