-- Migration: Create Marketing Insights Table
-- Description: Stores AI-generated strategic reports and analytical summaries by theme.

CREATE TYPE insight_category AS ENUM ('REVENUE', 'CONVERSION', 'USER_QUALITY', 'GROWTH', 'GENERAL');

CREATE TABLE IF NOT EXISTS public.dash_marketing_insights (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    category insight_category NOT NULL,
    title text NOT NULL,
    content text NOT NULL, -- Markdown content generated by AI
    summary text, -- Short summary for the card view
    metadata jsonb DEFAULT '{}', -- Stores raw stats used for the generation
    created_at timestamptz DEFAULT now()
);

-- Index for chronological reading
CREATE INDEX idx_marketing_insights_category ON public.dash_marketing_insights(category);
CREATE INDEX idx_marketing_insights_created_at ON public.dash_marketing_insights(created_at DESC);

-- Enable RLS
ALTER TABLE public.dash_marketing_insights ENABLE ROW LEVEL SECURITY;

-- Allow only authenticated users (admin/marketing) to view insights
CREATE POLICY "Authenticated users can read marketing insights" 
ON public.dash_marketing_insights FOR SELECT TO authenticated USING (true);

-- Allow admins to manage insights
CREATE POLICY "Admins can manage marketing insights" 
ON public.dash_marketing_insights FOR ALL TO authenticated USING (true);
